---
title: "Regional Voter Differences in the Folketing"
author: "Heidi Lucas" 
description: "Comparing Danish General Election Voting Patterns between Greenland and mainland Denmark" 

output:
  distill::distill_article:
    self_contained: false
---

## Project thoughts

How do regional differences in the voter population affect party support in the General Danish elections? In this study, I plan to examine voting patterns over time between four different voting regions during the Folketing, or General Danish Elections. Three of these regions are within Denmark (Hovedstaden, Midtjylland-Nordjylland, Sjælland-Syddanmark), and the other region is Greenland, an island nation that is part of the Kingdom of Denmark. I hypothesize that Greenlandic votes will differ significantly from Danish votes. Greenland is still one of the few countries that are partially controlled by a colonial government. Due to this unique regional and political structure, I expect that Greenlandic voters align more with left-leaning platforms, especially due to factors such as social structure, cultural norms, and the salience of more progressive views such as Greenlandic sovereignty. I will be using election data from Statistics Denmark and the Straubinger/folketingsvalg dataset. My explanatory variable will be voter region, categorized as Hovedstaden, Midtjylland-Nordjylland, Sjælland-Syddanmark, and Greenland. My outcome variable will be party votes, categorized by the different parties running within the election. To provide support for my hypothesis, there should be large regional differences in votes for different party platforms, especially for left-leaning platforms in Greenlandic voters. If there aren't large regional voting differences, in other words, Danish and Greenlandic voters display similar voting patterns, my hypothesis would be disproved.







